//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tecAirlinesEntities : DbContext
    {
        public tecAirlinesEntities()
            : base("name=tecAirlinesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aeronave> Aeronaves { get; set; }
        public virtual DbSet<Programa> Programas { get; set; }
        public virtual DbSet<Reserva> Reservas { get; set; }
        public virtual DbSet<Universidad> Universidads { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<Vuelo> Vueloes { get; set; }
        public virtual DbSet<Escala> Escalas { get; set; }
        public virtual DbSet<Promocion> Promocions { get; set; }
        public virtual DbSet<Tiquete> Tiquetes { get; set; }
    }
}
