//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Escala
    {
        public string C_Vuelo { get; set; }
        public string A_Salida { get; set; }
        public string A_Llegada { get; set; }
        public System.DateTime F_Salida { get; set; }
        public System.DateTime F_Llegada { get; set; }
    
        public virtual airport airport { get; set; }
        public virtual airport airport1 { get; set; }
        public virtual Vuelo Vuelo { get; set; }
    }
}
