//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public int Numero { get; set; }
        public int Contraseña { get; set; }
        public System.DateTime Expiracion { get; set; }
        public string Titular { get; set; }
        public int C_Reserva { get; set; }
    
        public virtual Reserva Reserva { get; set; }
    }
}
